import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="flex flex-col gap-1 underline text-blue-600">
            <Link href="next-safe-action">next-safe-action</Link>
            <Link href="orpc">orpc</Link>
            <Link href="orpc-rq">orpc + tanstack query</Link>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
